'use strict';
// Runs only after the user clicks the popup. It reads allowlisted public fields,
// never cookies, browser storage, page globals or private network responses.
function domesticCaptureParse(doc=document,pageUrl=location.href,stamp=new Date().toISOString()){
 const url=new URL(pageUrl);if(url.protocol!=='https:'||url.username||url.password||url.port)throw Error('只支持国内平台 HTTPS 商品详情页');
 const secretKey=key=>{const normalized=key.toLowerCase().replace(/[^a-z0-9]/g,'');return /token|cookie|auth|secret|session|password|credential|csrf/.test(normalized)||normalized.endsWith('signature')||['apikey','accesskey','privatekey','sign','signature'].includes(normalized);};
 if([...url.searchParams.keys()].some(secretKey))throw Error('商品地址含会话或凭据参数，请使用干净的商品详情地址');
 const matches=root=>url.hostname===root||url.hostname.endsWith('.'+root);
 let provider,productId;
 if(matches('1688.com')){provider='1688';productId=url.pathname.match(/^\/offer\/(\d{1,32})\.html$/)?.[1];url.search='';}
 else if(matches('taobao.com')||matches('tmall.com')){provider='taobao';if(['/item.htm','/item.html'].includes(url.pathname)&&url.searchParams.getAll('id').length===1)productId=url.searchParams.get('id');url.search=productId?'?id='+encodeURIComponent(productId):'';}
 else if(matches('yangkeduo.com')||matches('pinduoduo.com')){provider='pinduoduo';if(['/goods.html','/goods1.html','/goods2.html','/goods/detail'].includes(url.pathname)&&url.searchParams.getAll('goods_id').length===1)productId=url.searchParams.get('goods_id');url.search=productId?'?goods_id='+encodeURIComponent(productId):'';}
 if(!provider||!/^\d{1,32}$/.test(productId||''))throw Error('不支持此地址；请打开1688、淘宝或拼多多的明确商品详情页');
 url.hash='';
 const visible=e=>!!e&&e.getClientRects().length>0&&getComputedStyle(e).visibility!=='hidden'&&getComputedStyle(e).display!=='none';
 if([...doc.querySelectorAll('input[type="password"],[id*="captcha"],[class*="captcha"],[data-login-required]')].some(visible))throw Error('当前页面需要登录或验证码；请在浏览器自行完成，扩展不会绕过');
 const text=(v,max=1000)=>typeof v==='string'?v.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim().slice(0,max):'';
 const select=(selectors,requireBinding=false)=>{for(const selector of selectors){const e=doc.querySelector(selector);if(e&&(e.tagName==='META'||visible(e))&&currentNode(e,requireBinding)){const value=e.getAttribute('content')||e.getAttribute('data-sku-id')||e.getAttribute('data-product-title')||e.getAttribute('data-price-currency')||e.textContent;if(text(value))return text(value);}}return '';};
 const numeric=(value,whole=false)=>{if(typeof value==='number')return Number.isFinite(value)&&value>=0&&(!whole||Number.isInteger(value))?value:null;if(typeof value!=='string'||!/^\d+(?:\.\d+)?$/.test(value.trim()))return null;const n=Number(value);return !whole||Number.isInteger(n)?n:null;};
 const safeUrl=value=>{try{if(typeof value!=='string')return null;const u=new URL(value,pageUrl);if(u.protocol!=='https:'||u.username||u.password||u.port||[...u.searchParams.keys()].some(secretKey))return null;return u.href;}catch{return null;}};
 let product=null,method='visible-dom';const warnings=[];
 const bindsCurrent=value=>{let bound=false;for(const key of ['url','@id']){if(typeof value[key]!=='string')continue;try{const u=new URL(value[key],pageUrl);let pid;if(provider==='1688'&&(u.hostname==='1688.com'||u.hostname.endsWith('.1688.com')))pid=u.pathname.match(/^\/offer\/(\d{1,32})\.html$/)?.[1];else if(provider==='taobao'&&(u.hostname==='taobao.com'||u.hostname.endsWith('.taobao.com')||u.hostname==='tmall.com'||u.hostname.endsWith('.tmall.com')))pid=['/item.htm','/item.html'].includes(u.pathname)&&u.searchParams.getAll('id').length===1?u.searchParams.get('id'):null;else if(provider==='pinduoduo'&&(u.hostname==='yangkeduo.com'||u.hostname.endsWith('.yangkeduo.com')||u.hostname==='pinduoduo.com'||u.hostname.endsWith('.pinduoduo.com')))pid=['/goods.html','/goods1.html','/goods2.html','/goods/detail'].includes(u.pathname)&&u.searchParams.getAll('goods_id').length===1?u.searchParams.get('goods_id'):null;if(pid!==productId)return false;bound=true;}catch{return false;}}for(const key of ['productID','product_id','productId','itemId','goodsId']){if(value[key]!=null){if(String(value[key])!==productId)return false;bound=true;}}return bound;};
 const currentNode=(node,requireBinding=false)=>{let bound=false;for(let e=node,depth=0;e&&depth<80;e=e.parentElement,depth++){for(const key of ['data-product-id','data-item-id','data-goods-id']){if(e.hasAttribute(key)){const id=e.getAttribute(key);if(id!==productId){warnings.push('已忽略其他商品区域的可见字段（推荐商品不会归到当前商品）');return false;}bound=true;}}if(e.hasAttribute('data-product-url')){if(!bindsCurrent({url:e.getAttribute('data-product-url')})){warnings.push('已忽略无法绑定当前商品地址的可见区域');return false;}bound=true;}}if(requireBinding&&!bound){warnings.push('可见规格或字段缺少当前商品身份绑定，保持缺失供人工校对');return false;}return true;};
 const inspect=(value,depth=0)=>{if(depth>8||!value||typeof value!=='object'||product)return;if(Array.isArray(value)){for(const child of value.slice(0,500))inspect(child,depth+1);return;}const type=value['@type'];if(type==='Product'||Array.isArray(type)&&type.includes('Product')){if(bindsCurrent(value)){product=value;}else warnings.push('已忽略无法绑定当前商品编号的公开JSON商品；仅采用当前可见字段');return;}if(value.product&&typeof value.product==='object')inspect({...value.product,'@type':'Product'},depth+1);if(value['@graph'])inspect(value['@graph'],depth+1);};
 let budget=0;
 for(const node of [...doc.querySelectorAll('script[type="application/ld+json"],script[type="application/json"][data-product-json]')].slice(0,30)){const source=node.textContent||'';budget+=source.length;if(budget>4*1024*1024)break;try{inspect(JSON.parse(source));if(product){method=node.type==='application/ld+json'?'json-ld':'public-json';break;}}catch{}}
 const title=text(product?.name)||select(['[data-product-title]','[itemprop="name"]','h1','meta[property="og:title"]']);
 if(!title)throw Error('未读取到商品标题，可能需要登录或当前页面尚未载入；没有导出猜测资料');
 // Only explicit SKU-bearing offers or visible data-sku-id nodes establish variants.
 const nodes=[...doc.querySelectorAll('[data-sku-id]')].filter(e=>visible(e)&&currentNode(e,true)).slice(0,500);
 const offers=product?.offers?(Array.isArray(product.offers)?product.offers:[product.offers]):[];
 const explicit=offers.filter(o=>o&&typeof o==='object'&&typeof o.sku==='string'&&o.sku.trim()).slice(0,500);
 let variants=explicit.length?explicit.map(o=>({sku:text(o.sku,200),price:numeric(o.price),currency:text(o.priceCurrency||product?.offers?.priceCurrency,3).toUpperCase(),stock:numeric(o.inventoryLevel?.value??o.inventoryLevel,true)})):nodes.map(e=>({sku:text(e.getAttribute('data-sku-id'),200),price:numeric(e.getAttribute('data-price')),currency:text(e.getAttribute('data-currency')||select(['[data-price-currency]']),3).toUpperCase(),stock:numeric(e.getAttribute('data-stock'),true)}));
 if(!variants.length)variants=[{sku:text(product?.sku,200)||select(['[itemprop="sku"]'],true),price:numeric(offers[0]?.price)??null,currency:text(offers[0]?.priceCurrency||select(['[data-price-currency]']),3).toUpperCase(),stock:numeric(offers[0]?.inventoryLevel?.value??offers[0]?.inventoryLevel,true)}];
 const images=[];let sourceImages=product?.image;sourceImages=Array.isArray(sourceImages)?sourceImages:sourceImages?[sourceImages]:[];
 for(const value of [...sourceImages,...[...doc.querySelectorAll('meta[property="og:image"],[itemprop="image"],img[data-product-image]')].filter(e=>currentNode(e,e.tagName!=='META')).slice(0,50).map(e=>e.getAttribute('content')||e.getAttribute('src'))]){const image=safeUrl(typeof value==='object'?value.url:value);if(image&&!images.includes(image)&&images.length<50)images.push(image);else if(!image&&value)warnings.push('已忽略含凭据参数或不安全地址的图片引用');}
 const facts=[...doc.querySelectorAll('[data-product-fact]')].filter(e=>visible(e)&&currentNode(e,true)).slice(0,100).map(e=>text(e.textContent,150)).join('\n');
 const seen=new Map();for(const variant of variants){if(!seen.has(variant.sku))seen.set(variant.sku,variant);else if(JSON.stringify(seen.get(variant.sku))!==JSON.stringify(variant))throw Error('同一规格出现不同可见价格或库存，请先核对页面');}
 const items=[...seen.values()].map(v=>({product_id:productId,sku:v.sku,title,source_url:url.href,source_price:v.price,source_currency:v.currency||'',stock:v.stock,images,facts,supplier:select(['[data-supplier-name]'],true),brand:text(product?.brand?.name||product?.brand),captured_at:stamp,method}));
if(items.some(i=>i.source_currency!=='CNY'))warnings.push('币种未知或非人民币；保留实际币种，后台将阻止录入，请先核对网页');
 return {format:'noon-domestic-capture-v1',provider,captured_at:stamp,items,warnings:[...new Set(warnings)]};
}
if(typeof globalThis!=='undefined')globalThis.domesticCaptureParse=domesticCaptureParse;
