const assert = require('node:assert/strict');
const fs = require('node:fs');
const { randomUUID } = require('node:crypto');
const { runWorkflow } = require('./harness.cjs');

runWorkflow('after-sales registration -> quarantine receipt -> release -> original-currency refund expense', async ({page,call,navigate,settle,mobile}) => {
  const operation = (action, body) => call('/api/ops/'+action, {...body,request_id:randomUUID()});
  const warehouse = await operation('entity',{kind:'warehouse',name:'合成售后仓库'});
  const shop = await operation('entity',{kind:'shop',name:'合成售后店铺'});
  const imported = await call('/api/import',{products:[{title_zh:'合成售后夹子',source_url:'https://example.com/synthetic-return',source_sku:'SYNTHETIC-RETURN',brand:'合成品牌',facts:'仅用于临时数据浏览器测试',stock:10}]});
  assert.equal(imported.created.length,1);
  const pid = imported.created[0];
  await operation('adjust',{product_id:pid,warehouse_id:warehouse.id,direction:'in',quantity:10,reason:'合成售后测试初始库存'});
  let order = await operation('order',{shop_id:shop.id,warehouse_id:warehouse.id,external_id:'SYNTHETIC-AFTER-SALES-1',currency:'SAR',lines:[{product_id:pid,quantity:1,unit_price:'12.50'}]});
  order = await operation('reserve',{id:order.id,revision:order.revision});
  order = await operation('ship',{id:order.id,revision:order.revision,carrier:'合成测试承运商',tracking:'SYNTHETIC-TRACK-1'});
  assert.equal(order.revision,3);
  const operations = surface => call('/api/state?surface='+surface);
  const saleState = () => call('/api/after-sales/state');
  const stock = async () => (await operations('inventory')).ops.stock.find(s=>s.product_id===pid&&s.warehouse_id===warehouse.id);
  const savedOrder = async () => (await operations('orders')).ops.documents.find(d=>d.id===order.id);
  const finance = async () => (await operations('finance')).finance;
  assert.equal((await stock()).on_hand,9);

  await navigate('after-sales');
  await page.locator('#after-sales-create [name="order_id"]').selectOption(order.id);
  await page.locator(`#after-sales-create [name="quantity:${pid}"]`).waitFor();
  await page.locator('#after-sales-create [name="return_disposition"]').selectOption('quarantine');
  await page.locator('#after-sales-create [name="reason"]').fill('合成买家申请退货，待仓库核对');
  await page.locator(`#after-sales-create [name="quantity:${pid}"]`).fill('1');
  await page.locator('#after-sales-create button[type="submit"], #after-sales-create button:not([type])').click();
  await page.locator('#after-sales-preview').waitFor();
  assert.equal((await saleState()).total,0,'preview must not create a case');
  assert.equal(await page.locator('#after-sales-commit').isDisabled(),true);
  await mobile();

  const confirmPreview = async () => {
    await page.locator('#after-sales-preview').waitFor();
    assert.equal(await page.locator('#after-sales-commit').isDisabled(),true,'explicit confirmation is required');
    await mobile();
    await page.locator('#after-sales-confirm').check();
    assert.equal(await page.locator('#after-sales-commit').isDisabled(),false);
    await page.locator('#after-sales-commit').click();
    await page.locator('#after-sales-preview').waitFor({state:'detached'});
    await settle();
    return (await saleState()).rows[0];
  };
  let caseRow = await confirmPreview();
  const caseId = caseRow.id;
  assert.equal(caseRow.status,'registered');assert.equal(caseRow.revision,1);
  assert.equal(caseRow.order_revision,3);assert.equal((await savedOrder()).lines[0].returned,0);
  assert.equal((await stock()).on_hand,9,'registration must not return stock');
  assert.equal(caseRow.quarantine.length,0);

  const openCase = async formId => {
    const form=page.locator('#'+formId);
    const details=form.locator('xpath=ancestor::details');
    if(!await details.evaluate(element=>element.open))await details.locator('summary').click();
    await form.waitFor({state:'visible'});await mobile();return form;
  };
  let form=await openCase('as-receive-'+caseId);
  await form.locator('[name="evidence"]').fill('合成仓库实际收到1件，需隔离复核');
  await form.locator('button').click();
  await page.locator('#after-sales-preview').waitFor();
  assert.equal((await savedOrder()).lines[0].returned,0,'receipt preview must not alter the order');
  caseRow=await confirmPreview();
  assert.equal(caseRow.status,'received');assert.equal(caseRow.revision,2);assert.equal(caseRow.order_revision,4);
  assert.equal((await savedOrder()).lines[0].returned,1);
  assert.equal((await savedOrder()).returns.length,1);
  assert.equal((await stock()).on_hand,9,'quarantine cannot become available stock');
  assert.equal(caseRow.quarantine.length,1);assert.equal(caseRow.quarantine[0].received,1);assert.equal(caseRow.quarantine[0].remaining,1);

  form=await openCase('as-dispose-'+caseId);
  await form.locator('[name="disposition"]').selectOption('release');
  await form.locator(`[name="quantity:${pid}"]`).fill('1');
  await form.locator('[name="evidence"]').fill('合成人工复核：夹子完好，释放1件可用库存');
  await form.locator('button').click();
  await page.locator('#after-sales-preview').waitFor();
  assert.equal((await stock()).on_hand,9,'release preview cannot move inventory');
  caseRow=await confirmPreview();
  assert.equal(caseRow.revision,3);assert.equal(caseRow.quarantine[0].remaining,0);assert.equal(caseRow.quarantine[0].released,1);
  assert.equal((await stock()).on_hand,10);assert.equal((await stock()).reserved,0);
  assert.equal((await savedOrder()).revision,4);assert.equal((await savedOrder()).returns.length,1);
  assert.equal((await savedOrder()).lines[0].returned,1,'quarantine release must not append another order return');

  form=await openCase('as-refund-'+caseId);
  await form.locator('[name="category"]').selectOption('refund');
  await form.locator('[name="amount"]').fill('12.50');
  await form.locator('[name="fx"]').fill('1.9');
  await form.locator('[name="date"]').fill(new Date().toISOString().slice(0,10));
  await form.locator('[name="evidence_key"]').fill('synthetic-after-sales-refund-1');
  await form.locator('[name="evidence"]').fill('合成退款审核凭证，仅本地费用登记');
  await form.locator('[name="reason"]').fill('合成退货订单全额退款费用，未执行平台退款');
  await form.locator('button').click();
  await page.locator('#after-sales-preview').waitFor();
  assert.equal((await finance()).entries.length,0,'financial preview must not create an expense');
  assert.match(await page.locator('#after-sales-preview').innerText(),/SAR 12\.50/);
  caseRow=await confirmPreview();
  assert.equal(caseRow.revision,4);assert.equal(caseRow.order_revision,4);assert.equal(caseRow.money.refund_cents,1250);assert.equal(caseRow.money.remaining_cents,0);
  assert.equal(caseRow.platform_refund_sent,false);
  const financial = await finance();
  assert.equal(financial.entries.length,1);assert.equal(financial.payments.length,0,'a local expense must not record a payment');
  assert.equal(financial.entries[0].category,'refund');assert.equal(financial.entries[0].kind,'expense');
  assert.equal(financial.entries[0].currency,'SAR');assert.equal(financial.entries[0].amount_cents,1250);assert.equal(financial.entries[0].base_cents,2375);
  assert.equal(financial.entries[0].document_id,order.id);
  assert.equal((await stock()).on_hand,10);assert.equal((await savedOrder()).lines[0].returned,1);

  await page.locator('details summary').first().click();
  await mobile();
  const downloadEvent=page.waitForEvent('download');
  await page.locator('#after-sales-export').click();
  const download=await downloadEvent;
  assert.equal(download.suggestedFilename(),'after-sales.csv');
  const csv=fs.readFileSync(await download.path(),'utf8');
  assert.ok(csv.startsWith('\uFEFF'),'export must include UTF-8 BOM');
  assert.match(csv,/售后编号/);assert.ok(csv.includes(caseId));assert.ok(csv.includes('SYNTHETIC-AFTER-SALES-1'));
  assert.match(csv,/12\.50/);
  assert.equal((await finance()).entries.length,1,'export and mobile rendering cannot duplicate an expense');
}).catch(error=>{console.error(error);process.exitCode=1});
