const assert = require('node:assert/strict');
const {randomUUID} = require('node:crypto');
const {runWorkflow} = require('./harness.cjs');

runWorkflow('local alerts workflow', async ({page,call,navigate,settle,mobile}) => {
  const externalRequests=[];
  page.on('request',request=>{const url=new URL(request.url());if(['http:','https:'].includes(url.protocol)&&!['127.0.0.1','localhost'].includes(url.hostname))externalRequests.push(request.url());});
  const today=new Date().toISOString().slice(0,10);
  const shop=await call('/api/ops/entity',{request_id:randomUUID(),kind:'shop',name:'合成异常店铺'});
  const warehouse=await call('/api/ops/entity',{request_id:randomUUID(),kind:'warehouse',name:'合成异常仓库'});
  const supplier=await call('/api/ops/entity',{request_id:randomUUID(),kind:'supplier',name:'合成异常供应商'});
  const imported=await call('/api/import',{products:[{title_zh:'合成异常测试夹子',source_url:'https://example.com/alerts-fixture',source_sku:'ALERTS',facts:'黑色5件装',cost_cny:1,stock:10}]});
  const productId=imported.created[0];
  const order=await call('/api/ops/order',{request_id:randomUUID(),external_id:'SYNTHETIC-ALERT-ORDER',shop_id:shop.id,warehouse_id:warehouse.id,currency:'CNY',lines:[{product_id:productId,quantity:1,unit_price:'1.00'}]});
  const purchase=await call('/api/ops/purchase',{request_id:randomUUID(),supplier_id:supplier.id,warehouse_id:warehouse.id,lines:[{product_id:productId,quantity:1,unit_price:'1.00'}],note:'合成本地待收货，不向供应商发送'});
  for(let i=0;i<55;i++)await call('/api/finance/entry',{request_id:randomUUID(),kind:'expense',category:'other',currency:'CNY',amount:'1.00',fx:'1',date:today,evidence_key:'synthetic-alert-fee-'+i,evidence:'合成异常浏览器测试费用 '+i});
  const ledgerSnapshot=async()=>{
    const financial=(await call('/api/state?surface=finance')).finance;
    const inventory=(await call('/api/state?surface=inventory')).ops;
    return {cash:[financial.summary.cash_in_cents,financial.summary.cash_out_cents,financial.summary.cash_net_cents],payments:financial.payments,entries:financial.entries,stock:inventory.stock};
  };
  const before=await ledgerSnapshot();
  assert.deepEqual(before.cash,[0,0,0]);assert.deepEqual(before.stock,[]);
  await navigate('alerts');
  assert.equal((await call('/api/alerts/state')).counts.purchasing.total,1);
  assert.equal((await call('/api/alerts/state')).counts.finance.total,55);
  await page.locator('[data-alert-group="finance"]').click();await settle();
  await page.waitForFunction(()=>state.alerts?.group==='finance'&&state.alerts.rows.length===50);
  const first=await page.evaluate(()=>state.alerts);
  assert.equal(first.total,55);assert.equal(first.pages,2);
  await page.locator('#alerts-next').click();await settle();
  await page.waitForFunction(()=>state.alerts?.page===1);
  const second=await page.evaluate(()=>state.alerts);
  assert.equal(second.rows.length,5);assert.equal(second.total,55);
  assert.equal(first.rows.some(r=>second.rows.some(s=>s.key===r.key)),false);
  await page.locator('#alerts-prev').click();await settle();
  await page.waitForFunction(()=>state.alerts?.page===0);
  const selected=await page.evaluate(()=>state.alerts.rows[0]);
  const row=()=>page.locator('[data-alert-action="ack"][data-alert-row="0"]').locator('xpath=ancestor::tr');
  await row().locator('details summary').click();
  assert.ok((await row().locator('pre').innerText()).includes('allocated_cents'));
  assert.ok((await row().innerText()).includes(selected.target_id));
  await row().locator('[data-nav="finance"]').click();await settle();
  assert.equal(await page.evaluate(()=>view),'finance');
  await navigate('alerts');
  await page.locator('[data-alert-group="finance"]').click();await settle();
  // Without the explicit checkbox, clicking acknowledge must not issue a business or reminder write.
  await page.locator('[data-alert-action="ack"][data-alert-row="0"]').click();await settle();
  assert.equal((await call('/api/alerts/state?group=finance')).rows.find(r=>r.key===selected.key).mode,'open');
  await page.locator('#alerts-confirm').check();
  await page.locator('[data-alert-action="ack"][data-alert-row="0"]').click();await settle();
  await page.waitForFunction(key=>state.alerts.rows.find(r=>r.key===key)?.mode==='ack',selected.key);
  assert.equal(await page.locator('[data-alert-action="ack"][data-alert-row="0"]').isDisabled(),true);
  await page.locator('#alerts-confirm').check();
  await page.locator('[data-alert-hours="0"]').selectOption('1');
  await page.locator('[data-alert-action="snooze"][data-alert-row="0"]').click();await settle();
  await page.waitForFunction(key=>state.alerts.rows.find(r=>r.key===key)?.mode==='snooze',selected.key);
  const snoozed=(await call('/api/alerts/state?group=finance')).rows.find(r=>r.key===selected.key);
  assert.ok(Date.parse(snoozed.until)>Date.now());
  assert.deepEqual(await ledgerSnapshot(),before,'acknowledgement and snooze must not change cash, finance entries or inventory');
  const entry=before.entries.find(e=>e.id===selected.target_id);
  const changed=await call('/api/finance/allocate',{request_id:randomUUID(),id:entry.id,revision:entry.revision,allocations:[{order_id:order.id,amount:'0.50'}]});
  await page.locator('#alerts-refresh').click();await settle();
  await page.waitForFunction(key=>state.alerts.rows.find(r=>r.key===key)?.mode==='open',selected.key);
  const fresh=(await call('/api/alerts/state?group=finance')).rows.find(r=>r.key===selected.key);
  assert.notEqual(fresh.fingerprint,selected.fingerprint);assert.equal(fresh.evidence.allocated_cents,50);
  const stale=await page.evaluate(async args=>{
    const response=await fetch('/api/alerts/action',{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Token':state.token},body:JSON.stringify({key:args.key,fingerprint:args.fingerprint,mode:'ack',confirmed:true,request_id:crypto.randomUUID()})});
    return {status:response.status,result:await response.json()};
  },selected);
  assert.equal(stale.status,409);assert.ok(stale.result.error.includes('变化'));
  const afterAllocation=await ledgerSnapshot();assert.deepEqual(afterAllocation.cash,before.cash);assert.deepEqual(afterAllocation.payments,before.payments);assert.deepEqual(afterAllocation.stock,before.stock);
  await mobile();
  await row().locator('details summary').click();
  assert.equal(await row().locator('details').getAttribute('open'),'');
  await page.locator('#alerts-confirm').check();
  await page.locator('[data-alert-action="ack"][data-alert-row="0"]').click();await settle();
  await page.waitForFunction(key=>state.alerts.rows.find(r=>r.key===key)?.mode==='ack',selected.key);
  await page.locator('#alerts-confirm').check();
  await page.locator('[data-alert-hours="0"]').selectOption('24');
  await page.locator('[data-alert-action="snooze"][data-alert-row="0"]').click();await settle();
  await page.waitForFunction(key=>state.alerts.rows.find(r=>r.key===key)?.mode==='snooze',selected.key);
  await mobile();
  // Open an actual source edit form at 390px without saving any additional business action.
  await row().locator('[data-nav="finance"]').click();await settle();
  await page.locator('#fin-create summary').click();
  await page.locator('#fin-entry-form').waitFor();await mobile();
  await navigate('alerts');
  await page.locator('[data-alert-group="finance"]').click();await settle();
  await call('/api/finance/allocate',{request_id:randomUUID(),id:entry.id,revision:changed.revision,allocations:[{order_id:order.id,amount:'1.00'}]});
  await page.locator('#alerts-refresh').click();await settle();
  await page.waitForFunction(()=>state.alerts?.total===54);
  const resolved=await call('/api/alerts/state?group=finance');assert.equal(resolved.total,54);assert.equal(resolved.rows.some(r=>r.key===selected.key),false);
  await page.locator('[data-alert-group="purchasing"]').click();await settle();
  await page.waitForFunction(()=>state.alerts?.group==='purchasing');
  assert.equal(await page.evaluate(()=>state.alerts.rows[0].target_id),purchase.id);
  await mobile();
  const final=await ledgerSnapshot();assert.deepEqual(final.cash,before.cash);assert.deepEqual(final.stock,before.stock);assert.deepEqual(final.payments,before.payments);
  assert.deepEqual(externalRequests,[],'alerts must not contact external services or send messages');
  assert.equal((await call('/api/alerts/state')).events.length,4,'each confirmed desktop/mobile reminder action is audited once');
  console.log('Verified alerts: 55 finance rows paginated 50+5; explicit ack/snooze; source revision reopens; stale fingerprint HTTP 409; full allocation removes alert; cash/stock unchanged; 390px real ack/snooze, expanded source details and finance edit form; four audited actions and zero external requests.');
}).catch(error=>{console.error(error.stack||error);process.exitCode=1;});
