const assert = require('node:assert/strict');
const {runWorkflow} = require('./harness.cjs');

runWorkflow('SPU observed matrix, draft diagnostics, confirmed save and safe CSV',async({page,call,navigate,settle,mobile})=>{
  const imported=await call('/api/import',{products:Array.from({length:3},(_,i)=>({title_zh:`质检SKU${i}`,source_sku:`CG-${i}`,brand:'测试品牌',category:'test-category',facts:'矩阵原始事实'}))});
  const ids=imported.created;
  const before=(await call('/api/batch-editor/state')).rows;
  await navigate('catalog-groups');
  await page.locator('#catalog-group-form [name="name"]').fill('=CSV规格组');
  await page.locator('#cg-add-axis').click();
  await page.locator('[data-cg-axis="1"]').fill('尺寸');
  for(const id of ids)await page.locator(`[data-cg-add="${id}"]`).click();
  const combos=[['红','S'],['红','M'],['蓝','S']];
  for(let i=0;i<ids.length;i++)for(let a=0;a<2;a++)await page.locator(`[data-cg-value][data-pid="${ids[i]}"][data-axis="${a}"]`).fill(combos[i][a]);
  await page.locator(`[data-cg-value][data-pid="${ids[2]}"][data-axis="1"]`).fill('');
  await page.locator('#cg-diagnose').click();await settle();
  assert.ok((await page.locator('#cg-draft-quality').innerText()).includes('补充规格值：尺寸'));
  assert.equal((await call('/api/catalog-groups/state')).total,0,'diagnosis creates no group');
  await page.locator(`[data-cg-value][data-pid="${ids[2]}"][data-axis="1"]`).fill('S');
  assert.equal(await page.locator('#cg-draft-quality').count(),0,'edit invalidates old diagnosis');
  await page.locator('#catalog-group-form button[type="submit"]').click();await settle();
  const preview=await page.evaluate(()=>catalogGroupPreview);
  assert.equal(preview.group.quality.missing_combinations,1);
  assert.equal(await page.locator('#catalog-group-save').isDisabled(),true);
  await page.locator('#catalog-group-preview .cg-quality details summary').click();
  assert.ok((await page.locator('#catalog-group-preview').innerText()).includes('缺组合，仅提示'));
  await mobile();
  await page.locator('#catalog-group-confirm').check();await page.locator('#catalog-group-save').click();await settle();
  const saved=(await call('/api/catalog-groups/state')).rows[0];
  assert.equal(saved.members.length,3);assert.equal(saved.review_required,false);assert.equal(saved.noon_variants_published,false);
  const detail=page.locator('details.section-break').filter({has:page.locator(`[data-cg-edit="${saved.id}"]`)});
  await detail.locator(':scope > summary').click();
  await detail.locator('.cg-quality details summary').click();await mobile();
  const csvResponse=await page.request.get(new URL(`/api/catalog-groups/export?id=${saved.id}`,page.url()).href);
  assert.equal(csvResponse.status(),200);assert.ok(csvResponse.headers()['content-type'].includes('text/csv'));
  const csv=await csvResponse.text();assert.ok(csv.includes("'=CSV规格组"));assert.ok(csv.includes('缺口仅提示，不自动生成SKU'));
  assert.equal(await detail.locator('[data-cg-export]').count(),1);
  const after=(await call('/api/batch-editor/state')).rows;
  assert.deepEqual(after,before,'quality/save/export preserve product facts and approval state');
  await call(`/api/products/${ids[0]}/save`,{revision:1,data:{facts:'人工更新事实用于版本变更质检'}});
  await page.locator(`[data-cg-edit="${saved.id}"]`).click();
  await page.locator('#cg-diagnose').click();await settle();
  assert.ok((await page.locator('#cg-draft-quality').innerText()).includes('商品版本已变化'));
  assert.equal((await call('/api/catalog-groups/state')).rows[0].review_required,true);
  await mobile();
}).catch(error=>{console.error(error);process.exitCode=1});
