const assert=require('node:assert/strict');
const fs=require('node:fs');
const {runWorkflow}=require('./harness.cjs');

runWorkflow('domestic batch quality diagnostics',async({page,call,navigate,settle,mobile})=>{
 const account=await call('/api/channels/save',{provider:'1688',name:'合成质量诊断来源',base_url:'',config:{},enabled:true,revision:0});
 const item={product_id:'123456',sku:'ZERO',title:'=SUM(1,2)',source_url:'https://detail.1688.com/offer/123456.html',source_price:0,source_currency:'CNY',stock:0,images:['https://example.com/synthetic.png'],facts:'合成黑色5件装',supplier:'合成供应商',method:'visible-dom'};
 const pkg={format:'noon-domestic-capture-v1',provider:'1688',captured_at:'2026-10-03T12:00:00+00:00',warnings:['合成DOM规格需核对'],items:[item,{...item,product_id:'234567',source_url:'https://detail.1688.com/offer/234567.html',sku:'',source_price:null,stock:null,images:[],facts:'',supplier:''},{...item}]};
 const body={account_id:account.id,account_revision:account.revision,package:pkg};
 const preview=await call('/api/domestic-capture/preview',body);
 assert.equal(preview.quality_summary.total_rows,3);assert.equal(preview.quality_summary.unique_identities,2);
 assert.equal(preview.quality_summary.attention_rows,1);assert.equal(preview.rows[2].quality.duplicate_of_row,1);
 await navigate('domestic-capture');
 const upload=async data=>{
  await page.locator('#domestic-account').selectOption(account.id);
  await page.locator('#domestic-file').setInputFiles({name:'synthetic-quality.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});
  await page.locator('#domestic-preview').click();await settle();await page.locator('#domestic-quality-filter').waitFor();
 };
 await upload(pkg);
 assert.ok((await page.locator('#domestic-quality-summary').innerText()).includes('3 条观察'));
 assert.ok((await page.locator('[data-domestic-quality-row="1"]').innerText()).includes('网页售价：0 CNY'));
 assert.ok((await page.locator('[data-domestic-quality-row="2"]').innerText()).includes('真实规格货号未知'));
 await page.locator('#domestic-confirm').check();
 await page.locator('#domestic-quality-filter').selectOption('missing_source_sku');
 assert.equal(await page.locator('[data-domestic-quality-row]:visible').count(),1);
 assert.equal(await page.locator('#domestic-confirm').isChecked(),true,'filter preserves explicit confirmation');
 assert.ok((await page.locator('#domestic-quality-visible').innerText()).includes('完整资料包'));
 const firstDownload=page.waitForEvent('download');await page.locator('#domestic-quality-export').click();
 const firstCsv=fs.readFileSync(await (await firstDownload).path(),'utf8');
 assert.ok(firstCsv.startsWith('\uFEFF'));assert.ok(firstCsv.includes('"2","blocked"'));assert.ok(!firstCsv.includes('"1","new"'));
 assert.ok(firstCsv.includes("'=SUM(1,2)"),'CSV must neutralize source formula title');
 await mobile();
 await page.locator('[data-domestic-correction-details="2"] summary').click();
 await page.locator('[data-domestic-row="2"][data-domestic-correction="sku"]').fill('MANUAL-2');
 await page.locator('[data-domestic-row="2"][data-domestic-correction="evidence"]').fill('合成规格单第二行');
 assert.equal(await page.locator('#domestic-quality-export').isDisabled(),true);
 assert.equal(await page.locator('#domestic-confirm').isChecked(),false);
 await page.locator('#domestic-quality-filter').selectOption('all');
 assert.equal(await page.locator('[data-domestic-row="2"][data-domestic-correction="sku"]').inputValue(),'MANUAL-2');
 await page.locator('#domestic-corrections-preview').click();await settle();
 assert.equal(await page.locator('#domestic-quality-export').isDisabled(),false);
 assert.ok((await page.locator('[data-domestic-quality-row="2"]').innerText()).includes('网页原规格：未知'));
 const downloading=page.waitForEvent('download');await page.locator('#domestic-quality-export').click();
 const csv=fs.readFileSync(await (await downloading).path(),'utf8');assert.equal(csv.trim().split('\r\n').length,4);
 assert.ok(csv.includes('"0","0"'),'zero price and stock exported as explicit zeros');
 const escapeValues=await page.evaluate(()=>domesticDiagnosticCsv([{row:1,status:'new',raw:{external_product_id:'1',source_sku:'\t=1+1',title_zh:'@SUM(1)',source_url:'https://example.com',source_price:0,stock:0},capture:{method:'visible-dom',sku:'-2+3'},quality:{unknown_fields:[],issues:[],changed_fields:[]}}]));
 assert.ok(escapeValues.includes("'\t=1+1"));assert.ok(escapeValues.includes("'@SUM(1)"));assert.ok(escapeValues.includes("'-2+3"));
 await page.locator('#domestic-quality-filter').selectOption('duplicate_observation');assert.equal(await page.locator('[data-domestic-quality-row]:visible').count(),1);
 await page.locator('#domestic-confirm').check();await page.locator('#domestic-apply').click();await settle();
 const saved=await call('/api/collection/state');assert.equal(saved.total,2,'filtered confirmation still processes complete package');
 assert.equal((await call('/api/state')).products.length,0,'candidate confirmation cannot create products');
 const changed={...pkg,items:[{...item,source_price:9}]};await upload(changed);
 assert.ok((await page.locator('#domestic-preview-panel').innerText()).includes('与历史最新观察的变化'));
 await page.locator('#domestic-quality-filter').selectOption('history_conflict');assert.equal(await page.locator('[data-domestic-quality-row]:visible').count(),1);
 const conflict=await call('/api/domestic-capture/preview',{...body,package:changed});assert.deepEqual(conflict.rows[0].quality.changed_fields,[{field:'source_price',before:0,after:9}]);
 assert.equal((await call('/api/collection/state')).candidates.find(r=>r.raw.source_sku==='ZERO').raw.source_price,0,'preflight comparison is read only');
 await mobile();
 console.log('Verified batch unknown/zero diagnoses, original/manual SKU, duplicate first-row reference, historical changes, mobile filtering without lost drafts or approvals, actual filtered CSV download with formula neutralization, dirty export disabled, full-package candidate confirmation and no products. Synthetic local evidence only.');
}).catch(error=>{console.error(error.stack||error);process.exitCode=1;});
