const assert=require('node:assert/strict');
const fs=require('node:fs');
const {runWorkflow}=require('./harness.cjs');
runWorkflow('manual FX registry: versioned evidence, explicit direction/rounding, cancellation and safe history CSV',async({page,call,navigate,settle,mobile})=>{
 const factsBefore=(await call('/api/state')).products;
 await navigate('fx-registry');
 const fill=async(values)=>{for(const [k,v] of Object.entries(values))await page.locator(`#fx-registry-form [name="${k}"]`).fill(v)};
 const preview=async()=>{await page.locator('#fx-registry-form button').click();await page.locator('#fx-registry-preview').waitFor();assert.equal(await page.locator('#fx-registry-save').isDisabled(),true)};
 const save=async()=>{await page.locator('#fx-registry-confirm').check();await page.locator('#fx-registry-save').click();await page.locator('#fx-registry-preview').waitFor({state:'detached'});await settle()};
 const state=()=>call('/api/fx-registry/state');
 await fill({name:'=合成手录汇率',rate:'1.005',effective_from:'2026-01-01',effective_to:'2026-12-31',evidence:'合成人工来源凭据'});
 await preview();assert.equal((await state()).total,0,'preview cannot save');
 await page.locator('#fx-registry-confirm').check();await fill({rate:'1.9'});
 await page.locator('#fx-registry-preview').waitFor({state:'detached'});
 await fill({rate:'1.005'});await preview();await mobile();await save();
 let r=(await state()).rows[0];assert.equal(r.revision,1);assert.equal(r.from_currency,'SAR');assert.equal(r.to_currency,'CNY');
 const expand=async()=>{await page.locator(`[data-fx-details="${r.id}"] summary`).click();await page.locator('[data-fx-select="1"]').waitFor()};
 await expand();await page.locator('[data-fx-select="1"]').click();
 await page.locator('#fx-convert-form [name="amount"]').fill('1');await page.locator('#fx-convert-form [name="date"]').fill('2026-10-03');await page.locator('#fx-convert-form [name="rounding"]').selectOption('half_up');
 await page.locator('#fx-convert-form button').click();await page.waitForFunction(()=>document.getElementById('fx-convert-result').textContent.includes('1.01'));
 await page.locator('#fx-convert-form [name="rounding"]').selectOption('half_even');assert.equal(await page.locator('#fx-convert-result').innerText(),'');
 await page.locator('#fx-convert-form button').click();await page.waitForFunction(()=>document.getElementById('fx-convert-result').textContent.includes('1.00'));
 await page.locator(`[data-fx-edit="${r.id}"]`).click();await fill({rate:'2',evidence:'合成修订来源'});await preview();await save();
 r=(await state()).rows[0];assert.equal(r.revision,2);await expand();
 const get=await call('/api/fx-registry/get?id='+r.id);assert.equal(get.versions.length,2);assert.equal(get.versions[1].rate,'1.005');assert.equal(get.audit.length,2);
 const historical=await call('/api/fx-registry/convert',{id:r.id,revision:1,amount:'1',date:'2026-10-03',rounding:'half_up'});assert.equal(historical.converted_amount,'1.01');assert.equal(historical.accounting_written,false);
 const rejects=async(route,body)=>{const result=await page.evaluate(async a=>{try{await api(a.route,a.body);return false}catch(e){return e.message}},{route,body});assert.ok(result,'expected rejection')};
 await rejects('/api/fx-registry/convert',{id:r.id,revision:1,amount:'1',date:'2027-01-01',rounding:'half_up'});
 const cancel=page.locator(`[data-fx-cancel="${r.id}"]`);await cancel.locator('[name="reason"]').fill('合成撤销错误来源');await cancel.locator('[name="confirmed"]').check();await cancel.locator('[name="reason"]').fill('合成撤销整个档案');assert.equal(await cancel.locator('[name="confirmed"]').isChecked(),false);assert.equal(await cancel.locator('button').isDisabled(),true);
 await mobile();await cancel.locator('[name="confirmed"]').check();await cancel.locator('button').click();await settle();
 r=(await state()).rows[0];assert.equal(r.status,'cancelled');assert.equal(r.revision,3);
 for(const version of [1,2,3])await rejects('/api/fx-registry/convert',{id:r.id,revision:version,amount:'1',date:'2026-10-03',rounding:'half_up'});
 assert.deepEqual((await call('/api/state')).products,factsBefore);
 const download=page.waitForEvent('download');await page.locator('#fx-registry-export').click();const file=await download;assert.equal(file.suggestedFilename(),'fx-registry.csv');const csv=fs.readFileSync(await file.path(),'utf8');assert.ok(csv.startsWith('\uFEFF'));assert.ok(csv.includes("'=合成手录汇率"));assert.match(csv,/1\.005/);assert.match(csv,/合成撤销整个档案/);assert.match(csv,/仅展示不记账/);
}).catch(e=>{console.error(e);process.exitCode=1});
