const {clickNavigation}=require('./navigation_helpers.cjs');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const {runWorkflow} = require('./harness.cjs');

runWorkflow('confirmed physical inventory differences, stale preview and CSV', async ({page,call,navigate,settle,mobile}) => {
  const imported=await call('/api/import',{products:[
    {title_zh:'=合成实盘盒子',source_sku:'COUNT-A',supplier:'合成供应商',facts:'合成实盘产品A',stock:50},
    {title_zh:'合成首次开账盒子',source_sku:'COUNT-B',supplier:'合成供应商',facts:'合成实盘产品B',stock:null}
  ]});
  const [first,second]=imported.created;
  const warehouse=await call('/api/ops/entity',{kind:'warehouse',name:'合成盘点仓',request_id:'count-warehouse'});
  await call('/api/ops/adjust',{product_id:first,warehouse_id:warehouse.id,quantity:10,direction:'in',reason:'合成初始入库',request_id:'count-initial'});
  const stock=async()=>{
    const state=await call('/api/inventory-counts/state?warehouse_id='+warehouse.id);
    return {a:state.rows.find(r=>r.product_id===first),b:state.rows.find(r=>r.product_id===second),documents:state.documents};
  };
  await navigate('inventory-counts');
  await page.locator('#inventory-counts-warehouse').selectOption(warehouse.id);
  await settle();
  assert.ok((await page.locator('#main').innerText()).includes('未知 / 未建账'));
  const templateEvent=page.waitForEvent('download');
  await page.locator('#inventory-counts-template').click();
  const template=await templateEvent;
  assert.equal(template.suggestedFilename(),'库存实盘空白模板.csv');
  const templateBytes=fs.readFileSync(await template.path());
  assert.ok(templateBytes.subarray(0,3).equals(Buffer.from([0xef,0xbb,0xbf])),'template uses UTF8 BOM');
  assert.ok(templateBytes.toString('utf8').includes("'=合成实盘盒子"),'formula-like titles are escaped');
  assert.ok(templateBytes.toString('utf8').includes('counted_quantity'));
  await page.locator(`[data-inventory-count-select="${first}"]`).check();
  await page.locator(`[data-inventory-count-select="${second}"]`).check();
  assert.equal(await page.locator(`[data-inventory-count-quantity="${first}"]`).inputValue(),'','no invented physical count');
  assert.equal(await page.locator(`[data-inventory-count-quantity="${second}"]`).inputValue(),'');
  await page.locator('#inventory-counts-evidence').fill('合成验收：盘点人甲；2026-10-03；盘点记录GUI-1；不含隔离与在途');
  await page.locator('#inventory-counts-preview').click();
  await settle();
  const blankPre=await page.evaluate(()=>inventoryCountsPreview);
  assert.equal(blankPre.blocked,2);
  assert.equal(await page.locator('#inventory-counts-confirm').isDisabled(),true);
  assert.ok((await page.locator('#main').innerText()).includes('不会自动按0处理'));
  await page.locator(`[data-inventory-count-quantity="${first}"]`).fill('8');
  await page.locator(`[data-inventory-count-quantity="${second}"]`).fill('3');
  await page.locator('#inventory-counts-preview').click();
  await settle();
  let preview=await page.evaluate(()=>inventoryCountsPreview);
  assert.equal(preview.blocked,0);assert.equal(preview.changed,2);
  assert.equal(preview.rows.find(r=>r.product_id===first).delta,-2);
  assert.equal(preview.rows.find(r=>r.product_id===second).status,'opening');
  assert.equal(preview.rows.find(r=>r.product_id===second).on_hand,null);
  assert.equal(await page.locator('#inventory-counts-apply').isDisabled(),true);
  await page.locator('#inventory-counts-confirm').check();
  assert.equal(await page.locator('#inventory-counts-apply').isDisabled(),false,'consent remains checked when checking it');
  // A concurrent real ledger movement invalidates the already approved preview.
  await call('/api/ops/adjust',{product_id:first,warehouse_id:warehouse.id,quantity:1,direction:'in',reason:'合成并发收货',request_id:'count-concurrent'});
  const rejectedResponse=page.waitForResponse(response=>response.url().endsWith('/api/inventory-counts/apply')&&response.request().method()==='POST');
  await page.locator('#inventory-counts-apply').click();
  assert.equal((await rejectedResponse).status(),409);
  await settle();
  assert.equal(await page.locator('#inventory-counts-preview-panel').count(),0,'stale consent is revoked');
  let balances=await stock();
  assert.equal(balances.a.on_hand,11);assert.equal(balances.b.on_hand,null);assert.equal(balances.documents.length,0);
  await page.locator('#inventory-counts-preview').click();
  await settle();
  preview=await page.evaluate(()=>inventoryCountsPreview);
  assert.equal(preview.rows.find(r=>r.product_id===first).delta,-3);
  assert.equal(await page.locator('#inventory-counts-confirm').isChecked(),false);
  await mobile();
  // ops-scroll keeps the required count and confirmation columns accessible on mobile.
  assert.equal(await page.locator('#inventory-counts-preview-panel tbody tr').first().locator('td').nth(3).isVisible(),true);
  await page.locator('#inventory-counts-confirm').check();
  const appliedResponse=page.waitForResponse(response=>response.url().endsWith('/api/inventory-counts/apply')&&response.request().method()==='POST');
  await page.locator('#inventory-counts-apply').click();
  const applied=await (await appliedResponse).json();
  await settle();
  balances=await stock();
  assert.equal(balances.a.on_hand,8);assert.equal(balances.b.on_hand,3);assert.equal(balances.documents.length,1);
  assert.equal(applied.document.lines.find(r=>r.product_id===first).delta,-3);
  assert.equal(await page.locator('#inventory-counts-apply').isDisabled(),true);
  assert.equal(await page.evaluate(()=>dirty),false,'successful count saves clear the dirty draft');
  await mobile();
  const exportEvent=page.waitForEvent('download');
  await page.locator('#inventory-counts-result-export').click();
  const exported=await exportEvent;
  assert.equal(exported.suggestedFilename(),'库存实盘单.csv');
  const exportBytes=fs.readFileSync(await exported.path());
  assert.ok(exportBytes.subarray(0,3).equals(Buffer.from([0xef,0xbb,0xbf])));
  assert.ok(exportBytes.toString('utf8').includes("'=合成实盘盒子"));
  assert.ok(exportBytes.toString('utf8').includes("'-3"));

  // Exercise the actual uploaded CSV workflow and explicit zero, without rewriting unrelated stock.
  await page.locator('#inventory-counts-mode').selectOption('csv');
  await page.locator('#inventory-counts-file').setInputFiles({name:'synthetic-physical-count.csv',mimeType:'text/csv',buffer:Buffer.from('\ufeffproduct_id,counted_quantity\n'+second+',0\n')});
  await settle();
  assert.ok((await page.locator('#inventory-counts-csv').inputValue()).includes(second));
  await page.locator('#inventory-counts-evidence').fill('合成验收：盘点人甲；CSV实盘记录GUI-2；第二件良品实际为0');
  await page.locator('#inventory-counts-preview').click();
  await settle();
  preview=await page.evaluate(()=>inventoryCountsPreview);
  assert.equal(preview.rows.length,1);assert.equal(preview.rows[0].counted_quantity,0);assert.equal(preview.rows[0].delta,-3);
  await page.locator('#inventory-counts-confirm').check();
  await page.locator('#inventory-counts-apply').click();
  await settle();
  balances=await stock();
  assert.equal(balances.a.on_hand,8);assert.equal(balances.b.on_hand,0);assert.equal(balances.documents.length,2);
  const productState=await call('/api/batch-editor/state');
  assert.equal(productState.rows.find(r=>r.id===first).stock,50,'source stock is independent of physical warehouse count');
  await mobile();
  await page.locator('#inventory-counts-evidence').fill('尚未保存的新实盘草稿');
  assert.equal(await page.evaluate(()=>dirty),true);
  page.once('dialog',dialog=>dialog.dismiss());
  await clickNavigation(page,'products');
  await settle();
  assert.equal(await page.evaluate(()=>view),'inventory-counts','declining discard keeps the draft');
  assert.equal(await page.locator('#inventory-counts-evidence').inputValue(),'尚未保存的新实盘草稿');
  page.once('dialog',dialog=>dialog.accept());
  await navigate('products');
  assert.equal(await page.evaluate(()=>dirty),false);
  await navigate('inventory-counts');
  assert.equal(await page.locator('#inventory-counts-evidence').inputValue(),'');
  assert.equal(await page.evaluate(()=>inventoryCountRows.size),0);
  assert.equal(await page.evaluate(()=>inventoryCountsCSV),'');
  assert.equal((await stock()).documents.length,2,'discarding a draft does not write a count');
  await mobile();
}).catch(error=>{console.error(error);process.exitCode=1});
