const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {runWorkflow}=require('./harness.cjs');
runWorkflow('MiniMax subscription configuration, model menu and secret-free readback',async({page,navigate,settle,mobile})=>{
 await navigate('models');
 await page.locator('summary').filter({hasText:'新增模型服务'}).click();
 await page.locator('[name="provider"]').selectOption('minimax-subscription');
 assert.equal(await page.locator('[name="base_url"]').inputValue(),'https://api.minimax.cn/v1');
 assert.equal(await page.locator('[name="minimax_model"]').inputValue(),'MiniMax-M3');
 assert.equal(await page.locator('[name="input_price"]').isVisible(),false);
 fs.mkdirSync(path.resolve(__dirname,'../../output/playwright'),{recursive:true});
 await page.locator('#model-form').scrollIntoViewIfNeeded();
 await page.screenshot({path:path.resolve(__dirname,'../../output/playwright/minimax-subscription.png')});
 await page.locator('[name="name"]').fill('MiniMax 订阅测试');
 await page.locator('[name="api_key"]').fill('sk-cp-browser-synthetic-only');
 await page.locator('[name="enabled"]').check();
 await page.getByRole('button',{name:'保存服务配置',exact:true}).click();await settle();
 await page.getByRole('heading',{name:'MiniMax 订阅测试',exact:true}).waitFor();
 let state=await page.evaluate(()=>modelData());
 const profile=state.profiles.find(p=>p.name==='MiniMax 订阅测试');
 assert.equal(profile.provider,'minimax-subscription');assert.equal(profile.model,'MiniMax-M3');
 assert.equal(profile.context_limit,512000);assert.equal(profile.key_present,true);
 assert.equal(state.calls.length,0,'saving must never send a model request');
 assert.ok(!JSON.stringify(state).includes('sk-cp-browser-synthetic-only'));
 await page.locator(`[data-model-edit="${profile.id}"]`).click();
 assert.equal(await page.locator('[name="api_key"]').inputValue(),'');
 await page.locator('[name="minimax_model"]').selectOption('MiniMax-M3.1-Flash-Preview');
 await page.getByRole('button',{name:'保存服务配置',exact:true}).click();await settle();
 state=await page.evaluate(()=>modelData());assert.equal(state.profiles[0].model,'MiniMax-M3.1-Flash-Preview');assert.equal(state.profiles[0].key_present,true);
 await page.locator(`[data-model-edit="${profile.id}"]`).click();
 await page.locator('[name="minimax_model"]').selectOption('custom');
 await page.locator('[name="model"]').fill('MiniMax-future-model');
 await page.getByRole('button',{name:'保存服务配置',exact:true}).click();await settle();
 state=await page.evaluate(()=>modelData());assert.equal(state.profiles[0].model,'MiniMax-future-model');
 await page.locator(`[data-model-edit="${profile.id}"]`).click();
 assert.equal(await page.locator('[name="minimax_model"]').inputValue(),'custom');
 assert.equal(await page.locator('[name="model"]').inputValue(),'MiniMax-future-model');
 await mobile();assert.equal(await page.locator('[name="base_url"]').isVisible(),true);
 await page.locator('[name="provider"]').selectOption('codex-subscription');
 assert.equal(await page.locator('[name="api_key"]').isVisible(),false);
 assert.equal(await page.locator('[name="subscription_model"]').isVisible(),true);
});
