const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {runWorkflow}=require('./harness.cjs');

runWorkflow('compact navigation, disclosure, search, dirty-form protection and responsive layout',async({page,call,navigate,settle})=>{
 const output=path.resolve(__dirname,'../../output/playwright');fs.mkdirSync(output,{recursive:true});
 const activeSection=()=>page.locator('[data-nav-group][aria-expanded="true"]');
 const input=page.locator('#nav-search');
 assert.equal((await page.request.get(new URL('/navigation.js',page.url()).href)).status(),200);
 assert.equal(await page.locator('.nav [data-nav]').count(),40);
 assert.equal(await page.locator('.nav [data-nav]:visible').count(),5,'initial batch page exposes four daily routes and overview');
 assert.equal(await activeSection().count(),1);
 assert.equal(await activeSection().getAttribute('data-nav-group'),'catalog');
 await page.locator('[data-nav-group="finance"]').click();
 assert.equal(await activeSection().count(),1);assert.equal(await activeSection().getAttribute('data-nav-group'),'finance');
 assert.equal(await page.locator('main').getAttribute('data-view'),'batch','opening a menu must not navigate');
 await page.locator('[data-nav-subgroup="accounts"]').click();
 await page.locator('.nav [data-nav="bank-reconciliation"]').click();await settle();
 assert.equal(await activeSection().getAttribute('data-nav-group'),'finance');
 assert.equal(await page.locator('[data-nav-subgroup="accounts"]').getAttribute('aria-expanded'),'true');
 assert.match(await page.locator('.nav-breadcrumb').innerText(),/财务经营.*财务对账.*银行流水核对/s);
 await input.fill('1688');assert.equal(await page.locator('.nav [data-nav]').count(),2);
 assert.equal(await page.locator('.nav [data-nav]:visible').count(),2,'search reveals deep results');
 await page.locator('.nav [data-nav="domestic-capture"]').click();await settle();
 assert.equal(await input.inputValue(),'');assert.equal(await activeSection().getAttribute('data-nav-group'),'catalog');
 assert.equal(await page.locator('[data-nav-subgroup="sources"]').getAttribute('aria-expanded'),'true');
 await input.fill('没有这个功能abcdef');assert.equal(await page.locator('.nav [data-nav]').count(),0);
 assert.match(await page.locator('.nav-empty').innerText(),/清空搜索/);
 await input.press('Escape');assert.equal(await input.inputValue(),'');assert.equal(await input.evaluate(node=>node===document.activeElement),true);
 await input.fill('模型服务');assert.equal(await page.locator('.nav [data-nav]').count(),1);
 await input.press('Enter');await settle();
 assert.equal(await page.locator('main').getAttribute('data-view'),'models');
 assert.equal(await activeSection().getAttribute('data-nav-group'),'system');
 await page.locator('[data-nav-group="system"]').click();assert.equal(await activeSection().count(),0);
 await page.evaluate(()=>sync());assert.equal(await activeSection().count(),0,'data refresh must preserve a manually collapsed group');
 await navigate('batch');await page.screenshot({path:path.join(output,'navigation-desktop.png')});
 const measurements=[];
 for(const width of [1440,900,390]){
  await page.setViewportSize({width,height:900});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'navigation must not create document overflow');
  measurements.push(await page.evaluate(()=>({width:innerWidth,sidebar:document.querySelector('.sidebar').getBoundingClientRect().height,visibleRoutes:[...document.querySelectorAll('.nav [data-nav]')].filter(n=>n.getClientRects().length).length})));
 }
 assert.equal(await page.locator('#nav-mobile-toggle').getAttribute('aria-expanded'),'false');
 assert.equal(await input.isVisible(),false);assert.ok(await page.locator('.sidebar').evaluate(node=>node.getBoundingClientRect().height)<100);
 await page.screenshot({path:path.join(output,'navigation-mobile-closed.png')});
 await page.locator('#nav-mobile-toggle').click();assert.equal(await input.isVisible(),true);
 await page.screenshot({path:path.join(output,'navigation-mobile-open.png')});
 await input.fill('银行流水');await input.press('Enter');await settle();
 assert.equal(await page.locator('main').getAttribute('data-view'),'bank-reconciliation');
 assert.equal(await page.locator('#nav-mobile-toggle').getAttribute('aria-expanded'),'false');
 await page.locator('#nav-mobile-toggle').click();
 assert.equal(await page.locator('[data-nav-group="finance"]').getAttribute('aria-expanded'),'true');
 assert.equal(await page.locator('[data-nav-subgroup="accounts"]').getAttribute('aria-expanded'),'true');
 await page.setViewportSize({width:1440,height:900});
 const result=await call('/api/import',{products:[{title_zh:'导航回归合成商品'}]});
 await page.evaluate(()=>sync()); // API fixture seeding does not refresh the operator's catalog by itself.
 await navigate('products');await page.locator(`.product-name[data-open="${result.created[0]}"]`).click();
 await page.locator('#f-title_zh').fill('尚未保存的导航回归标题');
 await page.locator('[data-nav-group="orders"]').click();
 assert.equal(await page.locator('#f-title_zh').inputValue(),'尚未保存的导航回归标题');
 let dialogs=0;
 page.once('dialog',async dialog=>{dialogs++;await dialog.dismiss()});
 await page.locator('.nav [data-nav="orders"]').click();
 assert.equal(dialogs,1);assert.equal(await page.locator('main').getAttribute('data-view'),'products');
 assert.equal(await page.locator('#f-title_zh').inputValue(),'尚未保存的导航回归标题');
 await input.fill('不存在的功能');await input.press('Escape');
 assert.equal(await page.locator('#f-title_zh').inputValue(),'尚未保存的导航回归标题');
 page.once('dialog',dialog=>dialog.accept());await page.locator('.nav [data-nav="orders"]').click();await settle();
 assert.equal(await page.locator('main').getAttribute('data-view'),'orders');
 const saved=(await call('/api/state')).products.find(p=>p.id===result.created[0]);assert.equal(saved.title_zh,'导航回归合成商品','navigation must not save discarded drafts');
 fs.writeFileSync(path.join(output,'navigation-measurements.json'),JSON.stringify({routes:40,groups:6,measurements,real_noon_verified:false},null,2));
});
