const assert = require('node:assert/strict');
const fs = require('node:fs');
const { randomUUID } = require('node:crypto');
const { runWorkflow } = require('./harness.cjs');

runWorkflow('procurement GUI link -> stale receipt/cancellation -> confirmed unlink -> filtered analytics', async ({page,call,navigate,settle,mobile}) => {
  const op = (action,body) => call('/api/ops/'+action,{...body,request_id:randomUUID()});
  const shop=await op('entity',{kind:'shop',name:'合成关联SAR店'});
  const warehouse=await op('entity',{kind:'warehouse',name:'合成关联仓'});
  const supplier=await op('entity',{kind:'supplier',name:'合成采购供应商'});
  const imported=await call('/api/import',{products:[{title_zh:'合成采购关联夹子',source_url:'https://example.com/procurement-fixture',source_sku:'PROCUREMENT-FIXTURE',supplier:'合成采购供应商',facts:'仅用于本地自动化验证',cost_cny:2}]});
  const productId=imported.created[0];
  const order=await op('order',{shop_id:shop.id,warehouse_id:warehouse.id,external_id:'SYNTHETIC-PROCUREMENT-SAR',currency:'SAR',lines:[{product_id:productId,quantity:2,unit_price:'10'}]});
  const purchase=await op('purchase',{supplier_id:supplier.id,warehouse_id:warehouse.id,lines:[{product_id:productId,quantity:3,unit_price:'2'}]});
  const before=(await call('/api/state?surface=inventory')).ops;
  const financeBefore=(await call('/api/state?surface=finance')).finance;
  assert.deepEqual(before.stock,[]);
  assert.deepEqual(financeBefore.entries,[]);

  await navigate('procurement');
  await page.locator('[data-proc-demand]').first().click();
  await page.locator('#proc-purchase').selectOption(purchase.id);
  await page.locator('#proc-quantity').fill('2');
  await mobile(); // Expanded association form must also fit 390px.
  await page.locator('#proc-link-form button').click();
  await page.locator('#proc-confirm').waitFor();
  assert.match(await page.locator('#proc-editor').innerText(),/本次关联 2 件/);
  assert.deepEqual((await call('/api/procurement/state')).links,[],'preview must not create links');
  await page.locator('#proc-confirm').check();
  await page.locator('#proc-apply').click();
  await page.waitForFunction(async()=> (await api('/api/procurement/state')).links[0]?.quantity===2);
  await settle();
  const linked=await call('/api/procurement/state');
  assert.equal(linked.summary.confirmed_units,2);
  assert.equal(linked.summary.gap_units,0);
  assert.deepEqual((await call('/api/state?surface=inventory')).ops.stock,[],'linking must not add stock');
  assert.deepEqual((await call('/api/state?surface=finance')).finance.entries,[],'linking must not recognize costs');
  assert.deepEqual((await call('/api/state?surface=orders')).ops.documents,[order],'linking must not alter orders');
  const exportPromise=page.waitForEvent('download');
  await page.locator('#proc-export').click();
  const exported=await exportPromise;
  assert.equal(exported.suggestedFilename(),'noon-procurement-links.csv');
  assert.match(fs.readFileSync(await exported.path(),'utf8'),/SYNTHETIC-PROCUREMENT-SAR/);

  const received=await op('receive',{id:purchase.id,revision:purchase.revision,quantities:{[productId]:1}});
  await page.locator('#proc-refresh').click();
  await page.waitForFunction(()=>state.procurement.links[0]?.needs_review===1);
  assert.match(await page.locator('#main').innerText(),/采购事实或到货数量已变化/);
  assert.equal((await call('/api/procurement/state')).summary.confirmed_units,0);
  const cancelled=await op('cancel',{id:purchase.id,revision:received.revision,reason:'合成供应商取消未到货部分'});
  await page.locator('#proc-refresh').click();
  await page.waitForFunction(()=>state.procurement.links[0]?.current_purchase_revision===3);
  assert.match(await page.locator('#main').innerText(),/采购已取消，仅已收货量可重新关联/);
  const beforeUnlink=(await call('/api/state?surface=inventory')).ops;
  assert.equal(beforeUnlink.stock[0].on_hand,1);
  await page.locator('[data-proc-unlink]').first().click();
  await page.locator('#proc-confirm').waitFor();
  assert.match(await page.locator('#proc-apply').innerText(),/确认解除关联/);
  await mobile();
  assert.equal((await call('/api/procurement/state')).links.length,1,'unlink preview must not release capacity');
  await page.locator('#proc-confirm').check();
  await page.locator('#proc-apply').click();
  await page.waitForFunction(async()=> (await api('/api/procurement/state')).links.length===0);
  await settle();
  assert.deepEqual((await call('/api/state?surface=inventory')).ops.stock,beforeUnlink.stock,'unlink must preserve received stock');
  assert.deepEqual((await call('/api/state?surface=orders')).ops.documents,[order],'unlink must preserve orders');
  assert.deepEqual((await call('/api/state?surface=purchases')).ops.documents,[cancelled],'unlink must preserve cancellation and receipt evidence');
  assert.deepEqual((await call('/api/state?surface=finance')).finance.entries,[]);

  // Real form filtering must preserve currencies and avoid inventing revenue.
  const otherShop=await op('entity',{kind:'shop',name:'合成关联USD店'});
  const otherWarehouse=await op('entity',{kind:'warehouse',name:'合成关联第二仓'});
  await op('order',{shop_id:otherShop.id,warehouse_id:otherWarehouse.id,external_id:'SYNTHETIC-PROCUREMENT-USD',currency:'USD',lines:[{product_id:productId,quantity:1,unit_price:'7'}]});
  await navigate('analytics');
  await page.locator('#analytics-filter').waitFor();
  const today=new Date().toISOString().slice(0,10);
  await page.locator('#analytics-from').fill(today);
  await page.locator('#analytics-to').fill(today);
  await page.locator('#analytics-filter button').click();
  await page.waitForFunction(()=>state.analytics.filters.from===new Date().toISOString().slice(0,10));
  assert.deepEqual(await page.evaluate(()=>Object.fromEntries(state.analytics.order_currencies.map(c=>[c.currency,c.amount_cents]))),{SAR:2000,USD:700});
  await page.locator('#analytics-shop').selectOption(shop.id);
  await page.locator('#analytics-warehouse').selectOption(warehouse.id);
  await page.locator('#analytics-filter button').click();
  await page.waitForFunction(ids=>state.analytics.filters.shop_id===ids.shop&&state.analytics.filters.warehouse_id===ids.warehouse,{shop:shop.id,warehouse:warehouse.id});
  const scoped=await page.evaluate(()=>state.analytics);
  assert.equal(scoped.orders.total,1);
  assert.deepEqual(scoped.order_currencies,[{currency:'SAR',orders:1,amount_cents:2000}]);
  assert.equal(scoped.inventory.on_hand,1);
  assert.equal(scoped.finance.income_cents,0);
  assert.match(await page.locator('#main').innerText(),/非净利润/);
  await mobile();
  const analyticsDownload=page.waitForEvent('download');
  await page.locator('#analytics-export').click();
  assert.match((await analyticsDownload).suggestedFilename(),/^noon-analytics-.*\.csv$/);
  await page.locator('#analytics-shop').selectOption(otherShop.id);
  await page.locator('#analytics-warehouse').selectOption(otherWarehouse.id);
  await page.locator('#analytics-filter button').click();
  await page.waitForFunction(id=>state.analytics.filters.shop_id===id,otherShop.id);
  assert.deepEqual(await page.evaluate(()=>state.analytics.order_currencies),[{currency:'USD',orders:1,amount_cents:700}]);
  assert.equal(await page.evaluate(()=>state.analytics.inventory.on_hand),0);
  await mobile();
}).catch(error=>{console.error(error);process.exitCode=1});
