const assert=require('node:assert/strict');
const fs=require('node:fs');
const {runWorkflow}=require('./harness.cjs');
runWorkflow('manual replenishment policy, stale sources, pagination and filtered CSV',async({page,call,navigate,settle,mobile})=>{
 const imported=await call('/api/import',{products:[{title_zh:'=合成补货盒子',source_sku:'REPL-A',supplier:'合成供货',facts:'补货合成测试'},...Array.from({length:54},(_,i)=>({title_zh:'合成补货分页'+i,source_sku:'REPL-'+i,supplier:'合成供货',facts:'补货分页测试'}))]});
 const pid=imported.created[0];
 const wh=await call('/api/ops/entity',{kind:'warehouse',name:'合成补货仓',request_id:'r-wh'});
 const supplier=await call('/api/ops/entity',{kind:'supplier',name:'合成供应商',request_id:'r-supplier'});
 await call('/api/ops/adjust',{product_id:pid,warehouse_id:wh.id,quantity:10,direction:'in',reason:'合成入库',request_id:'r-stock'});
 const purchase=await call('/api/ops/purchase',{supplier_id:supplier.id,warehouse_id:wh.id,lines:[{product_id:pid,quantity:8,unit_price:'2'}],request_id:'r-purchase'});
 await navigate('replenishment');
 await page.locator('#replenishment-warehouse').selectOption(wh.id);
 await page.locator('#replenishment-filter button').click();await settle();
 assert.equal(await page.locator('[data-replenishment-edit]').count(),50);
 await page.locator('[data-replenishment-page="1"]').click();await settle();
 assert.equal(await page.locator('[data-replenishment-edit]').count(),5);
 await page.locator('#replenishment-search').fill('=合成补货盒子');
 await page.locator('#replenishment-filter button').click();await settle();
 assert.equal(await page.locator('[data-replenishment-edit]').count(),1);
 assert.ok((await page.locator('#main').innerText()).includes('未知'));
 await page.locator('[data-replenishment-edit]').click();
 assert.equal(await page.locator('#replenishment-target').inputValue(),'');
 await page.locator('#replenishment-minimum').fill('12');await page.locator('#replenishment-target').fill('30');await page.locator('#replenishment-lead_days').fill('7');
 await page.locator('#replenishment-note').fill('合成参数；人工确认，无销售预测');
 await page.locator('#replenishment-preview').click();await settle();
 let pre=await page.evaluate(()=>replenishmentPreview);assert.equal(pre.quantity,12);assert.equal(pre.purchase_pending,8);
 assert.equal(await page.locator('#replenishment-apply').isDisabled(),true);
 await page.locator('#replenishment-confirm').check();
 await call('/api/ops/adjust',{product_id:pid,warehouse_id:wh.id,quantity:1,direction:'in',reason:'合成并发入库',request_id:'r-concurrent'});
 const rejection=page.waitForResponse(r=>r.url().endsWith('/api/replenishment/apply')&&r.request().method()==='POST');
 await page.locator('#replenishment-apply').click();assert.equal((await rejection).status(),409);await settle();
 assert.equal(await page.locator('#replenishment-preview-panel').count(),0);
 await page.locator('#replenishment-preview').click();await settle();
 pre=await page.evaluate(()=>replenishmentPreview);assert.equal(pre.quantity,11);assert.equal(await page.locator('#replenishment-confirm').isChecked(),false);

 await mobile();await page.locator('#replenishment-confirm').check();
 let replayBody;page.on('request',r=>{if(r.url().endsWith('/api/replenishment/apply')&&r.method()==='POST')replayBody=r.postDataJSON()});
 const success=page.waitForResponse(r=>r.url().endsWith('/api/replenishment/apply')&&r.request().method()==='POST');
 await page.locator('#replenishment-apply').click();const response=await success;assert.equal(response.status(),200);await settle();
 assert.equal(await page.evaluate(()=>dirty),false);
 const saved=await call('/api/replenishment/state?warehouse_id='+wh.id+'&search='+encodeURIComponent('=合成补货盒子'));assert.equal(saved.rows[0].quantity,11);assert.equal(saved.rows[0].revision,1);
 const replay=await call('/api/replenishment/apply',replayBody);assert.equal(replay.revision,1,'exact saved request replays without increment');
 // Receiving raises good stock and lowers actual purchase pending equally.
 await call('/api/ops/receive',{id:purchase.id,revision:purchase.revision,quantities:{[pid]:3},request_id:'r-receive'});
 await page.locator('#replenishment-refresh').click();await settle();
 const current=await page.evaluate(()=>state.replenishment.rows[0]);assert.equal(current.available,14);assert.equal(current.purchase_pending,5);assert.equal(current.quantity,11);assert.notEqual(current.source_version,saved.rows[0].source_version);
 const download=page.waitForEvent('download');await page.locator('#replenishment-export').click();const exported=await download;
 const bytes=fs.readFileSync(await exported.path());assert.ok(bytes.subarray(0,3).equals(Buffer.from([0xef,0xbb,0xbf])));assert.ok(bytes.toString().includes("'=合成补货盒子"));assert.ok(!bytes.toString().includes('合成补货分页'));assert.ok(bytes.toString().includes(purchase.id));
 await mobile();
 const snapshot=await call('/api/state?surface=purchases');assert.equal(snapshot.ops.documents.filter(d=>d.kind==='purchase').length,1,'suggestions never generate purchasing documents');
});
