const assert=require('node:assert/strict');
const fs=require('node:fs');
const {randomUUID}=require('node:crypto');
const {runWorkflow}=require('./harness.cjs');

runWorkflow('物流包装草稿 -> 来源失效 -> 修订防重 -> 实测交接与安全CSV',async({page,call,navigate,settle,mobile})=>{
  let detailRequests=0;page.on('request',request=>{if(request.url().includes('/api/shipping-manifests/get?'))detailRequests++});
  const op=(action,body)=>call('/api/ops/'+action,{...body,request_id:randomUUID()});
  const shop=await op('entity',{kind:'shop',name:'合成物流店铺'});
  const warehouse=await op('entity',{kind:'warehouse',name:'合成物流仓库'});
  const imported=await call('/api/import',{products:[{title_zh:'@合成包装商品',facts:'合成测试专用',source_sku:'PACKING-FIXTURE',cost_cny:2}]});
  const productId=imported.created[0];
  await op('adjust',{product_id:productId,warehouse_id:warehouse.id,quantity:10,direction:'in',reason:'合成物流期初10件'});
  let order=await op('order',{shop_id:shop.id,warehouse_id:warehouse.id,external_id:'SYNTHETIC-SHIPPING-1',currency:'SAR',lines:[{product_id:productId,quantity:2,unit_price:'10'}]});
  order=await op('reserve',{id:order.id,revision:order.revision});
  order=await op('ship',{id:order.id,revision:order.revision,carrier:'合成承运商',tracking:'SYNTHETIC-TRACKING-1'});
  const stock=async()=> (await call('/api/state?surface=inventory')).ops.stock[0];
  assert.equal((await stock()).on_hand,8);
  await navigate('shipping-manifests');
  await page.locator(`[data-shipping-manifest-order="${order.id}"]`).check();
  const field=k=>page.locator(`[data-shipping-package="${order.id}"][data-shipping-field="${k}"]`);
  await field('box_no').fill('=SYNTHETIC-BOX');
  for(const [k,v]of [['length_cm','20'],['width_cm','10'],['height_cm','5']])await field(k).fill(v);
  page.once('dialog',dialog=>dialog.dismiss());await page.locator('.nav [data-nav="orders"]').click();
  assert.equal(await page.evaluate(()=>view),'shipping-manifests');assert.equal(await field('box_no').inputValue(),'=SYNTHETIC-BOX');
  await mobile();
  await page.locator('#shipping-manifest-preview').click();await settle();
  await page.locator('#shipping-manifest-confirm').waitFor();
  assert.match(await page.locator('#shipping-manifest-preview-panel').innerText(),/待实测/);
  assert.equal(await page.locator('#shipping-manifest-apply').isDisabled(),true);
  assert.equal((await call('/api/shipping-manifests/state')).total,0);
  await page.locator('#shipping-manifest-confirm').check();await page.locator('#shipping-manifest-apply').click();await settle();
  let saved=(await call('/api/shipping-manifests/state')).manifests[0];
  assert.equal(detailRequests,0,'summary listing must not automatically load full manifests');
  for(const key of ['packages','order_ids','source_fingerprint','audit'])assert.equal(key in saved,false);
  assert.equal(saved.revision,1);assert.equal(saved.missing_count,1);
  assert.equal(await page.locator('[data-shipping-handoff]').count(),0);
  await page.locator('[data-shipping-details]').first().click();await settle();
  assert.equal(detailRequests,1);await page.locator('[data-shipping-details]').first().click();await settle();
  await page.locator('[data-shipping-details]').first().click();await settle();assert.equal(detailRequests,1,'reopening the same revision should reuse cache');
  assert.equal(await page.locator('[data-shipping-handoff] button').isDisabled(),true);
  await page.locator('[data-shipping-edit]').first().click();
  await field('weight_kg').fill('0.25');
  await page.locator('#shipping-manifest-preview').click();await settle();await page.locator('#shipping-manifest-confirm').check();
  await field('length_cm').fill('21');
  assert.equal(await page.locator('#shipping-manifest-preview-panel').isVisible(),false,'changing a measurement must invalidate confirmation');
  await page.locator('#shipping-manifest-preview').click();await settle();await page.locator('#shipping-manifest-confirm').check();
  await op('adjust',{product_id:productId,warehouse_id:warehouse.id,quantity:1,direction:'in',reason:'合成来源库存改变'});
  await page.locator('#shipping-manifest-apply').click();await settle();
  assert.match(await page.locator('#toast').innerText(),/重新预检/);
  assert.equal((await call('/api/shipping-manifests/state')).manifests[0].revision,1);
  await page.locator('#shipping-manifest-preview').click();await settle();await page.locator('#shipping-manifest-confirm').check();
  const confirmed=await page.evaluate(()=>({...shippingManifestRequest}));
  await page.locator('#shipping-manifest-apply').click();await settle();
  saved=(await call('/api/shipping-manifests/state')).manifests[0];assert.equal(saved.revision,2);
  const replay=await call('/api/shipping-manifests/apply',confirmed);assert.equal(replay.id,saved.id);assert.equal(replay.revision,2);
  assert.equal((await call('/api/shipping-manifests/state')).total,1);
  const stale=await page.evaluate(async body=>{try{await api('/api/shipping-manifests/handoff',body);return ''}catch(e){return e.message}},{id:saved.id,revision:1,recipient:'旧版本接收人',evidence:'旧版本不能交接',confirmed:true,request_id:randomUUID()});
  assert.match(stale,/版本已变化/);
  await page.locator(`[data-shipping-details="${saved.id}"]`).click();await settle();
  const form=page.locator(`[data-shipping-handoff="${saved.id}"]`);
  await page.locator('summary').filter({hasText:'登记实际交接'}).click();
  await form.locator('[name="recipient"]').fill('合成仓库交接接收人');
  await page.evaluate(()=>sync());await settle();assert.equal(await form.locator('[name="recipient"]').inputValue(),'合成仓库交接接收人');
  await page.locator('summary').filter({hasText:'登记实际交接'}).click();
  await form.locator('[name="evidence"]').fill('合成实际交接记录TEST-001');
  await form.locator('[name="confirmed"]').check();await mobile();
  await form.locator('button').click();await settle();
  saved=(await call('/api/shipping-manifests/state')).manifests[0];assert.equal(saved.status,'handed_off');assert.equal(saved.revision,3);assert.equal((await call('/api/shipping-manifests/get?id='+saved.id)).audit.length,3);
  assert.equal((await stock()).on_hand,9);assert.equal((await stock()).reserved,0);
  assert.equal((await call('/api/state?surface=orders')).ops.documents[0].status,'shipped','handoff must not mark buyer delivery');
  assert.deepEqual((await call('/api/state?surface=finance')).finance.entries,[]);
  for(const kind of ['packages','sku','handoff']){
    const pending=page.waitForEvent('download');await page.locator(`[data-shipping-export="${saved.id}"][data-shipping-kind="${kind}"]`).click();
    const download=await pending;const csv=fs.readFileSync(await download.path(),'utf8');
    assert.ok(csv.startsWith('\ufeff'));assert.ok(csv.includes("'=SYNTHETIC-BOX"));assert.ok(csv.includes('不是承运商电子面单'));
    if(kind==='sku')assert.ok(csv.includes("'@合成包装商品"));
    if(kind==='handoff')assert.ok(csv.includes('合成实际交接记录TEST-001'));
  }
  await op('adjust',{product_id:productId,warehouse_id:warehouse.id,quantity:1,direction:'in',reason:'合成已交接后的新库存'});
  await page.evaluate(()=>sync());await settle();
  assert.match(await page.locator('main').innerText(),/历史版本/);
  await mobile();
}).catch(error=>{console.error(error);process.exitCode=1});
